# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "83778577e3ab0812bff3c1a9b6e2b070"
name = "my-new-store"
handle = "my-new-store-7"
application_url = "https://keyboards-insurance-colleague-human.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "react-node-helixo-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://keyboards-insurance-colleague-human.trycloudflare.com/auth/callback",
  "https://keyboards-insurance-colleague-human.trycloudflare.com/auth/shopify/callback",
  "https://keyboards-insurance-colleague-human.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
